package hu.bme.mobsoft.marvelheroes.network.api

/**
 * Marvel marvelComics
 * This is a home work
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import hu.bme.mobsoft.marvelheroes.network.model.MarvelCharacterResponse
import retrofit2.Call
import retrofit2.http.GET
import retrofit2.http.Path
import retrofit2.http.Query

interface ComicApi {

    /**
     * Get a comic
     *
     * @param ts
     * @param hash
     * @param apikey
     * @param comicId ID of comic to return
     * @return void
     */

    @GET("commics/{comicId}")
    fun getComic(
        @Path("comicId") comicId: String,
        @Query("ts") ts: Int,
        @Query("hash") hash: String,
        @Query("apikey") apikey: String
    ): Call<MarvelCharacterResponse>

}
